name: apk_service_check
description: Aplicación que permitirá exportar a pdf.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter  


 
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  google_fonts: ^6.1.0
  url_launcher: ^6.1.14
  dio: ^5.4.0
  permission_handler: ^11.0.1
  open_file: ^3.3.2
  file_utils: ^1.0.1
  device_info_plus: ^9.1.1
  path_provider: ^2.1.2
  table_calendar: ^3.0.9
  animate_do: ^3.0.2


dev_dependencies:
  get: ^4.6.5  


  flutter_lints: ^3.0.1

flutter: 
  uses-material-design: true
  generate: true
 
 
      
  
